redis:
  address: ${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:number:-6379}
limits:
  interval: ${LIMIT_INTERVAL:number:-10}
  anonymous: ${LIMIT_ANONYMOUS:number:-10}
  identified: ${LIMIT_IDENTIFIED:number:-60}
  other:
    system: 0
identifiers:
  - jwtBearerHeader:
      algorithm: HS256
      verifier: EyllPgDqUmu9T+ununAWNL02fKXjQfo+QWQNpqDU6TA=
      claim: sub
