name: test
on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --entrypoint redis-server
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v2
    - run: go test ./internal
